"""Add Review Model

Revision ID: acebca3d5a50
Revises: c51cfcd150c0
Create Date: 2023-10-30 15:04:17.015280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acebca3d5a50'
down_revision = 'c51cfcd150c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
